### ISSUE TITLE
Uploading again in IE fails

### ISSUE THREAD

**Issue by leon** [leon/angular-upload#1]
When pressing upload button it works the first time, but it will not upload the second time :(

**Comment by Izzmo** [comment]
So.. I fixed this bug, and it works in all browsers, by just removing the scope.$apply(function ...) and just calling scope.onUpload({ files: fileInput[0].files }); directly.

Why do we need the .$apply?

**Comment by lombcar** [comment]
Here is my html:
 
<script src="/mm/js/devel/modules/angular-upload.js"></script>
<body ng-app="MyApp" ng-controller="SummaryController">
<div
						  class="button-file button oro medium"
						  style="width:18%"
						  upload-button
						  data="uploadData"
						  url="/bff/documents"
						  on-upload="onFileSelect(files,'carta')"
						  on-success="onFileSuccess(response)"
						>UPLOAD
				   </div>




But not work with IE9 in console i find this error:
Failed to instantiate module lr.upload due to:
[$injector:nomod] Module 'lr.upload' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.25/$injector/nomod?p0=lr.upload
http://errors.angularjs.org/1.2.25/$injector/modulerr?p0=lr.upload&p1=%5B%24injector%3Anomod%5D%20Module%20'lr.upload'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.2.25%2F%24injector%2Fnomod%3Fp0%3Dlr.upload
http://errors.angularjs.org/1.2.25/$injector/modulerr?p0=BffApp&p1=%5B%24injector%3Amodulerr%5D%20F

Can you help me ?
Many thanks

**Comment by fantapop** [comment]
I'm experiencing the same issue, but calling scope.onUpload does not fix it for me.  Neither in ie9 nor in Chrome latest.

```
-scope.$apply(function () {
-    scope.onUpload({ files: fileInput[0].files });
-});
+scope.onUpload({ files: fileInput[0].files });
```

@Izzmo  is this the diff you're using to fix it?

**Comment by fantapop** [comment]
oh, also, this would not apply to browser that don't use the file api such as IE 9

**Comment by Izzmo** [comment]
@fantapop yep, and it's been working for me.

**Comment by fantapop** [comment]
by the way, I worked around this issue but adding an ng-if outside the element with the uploader on it cycling it false and then true again. This full resets the element.  It works well.

**Comment by Izzmo** [comment]
Example?
